- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Install helper packages
  ansible.builtin.package:
    name: 
      - software-properties-common
      - dirmngr
    state: present

- name: Install r base and prerequisites for rstudio server
  ansible.builtin.package:
    name: 
      - r-base
      - gdebi-core
      - r-base-dev
    state: present

- name: Install rstudio .deb package from the internet
  ansible.builtin.apt:
    deb: "{{ rstudio_server_deb_url }}" 
    state: present

- name: Install R shiny package
  ansible.builtin.package:
    name: r-cran-shiny
    state: present 

- name: Install shiny server .deb package from the internet
  ansible.builtin.apt:
    deb: "{{ shiny_server_deb_url }}"
    state: present

